server:
  port: 8600

logging:
  path: .
  file: log.log

spring:
  datasource:
    url: jdbc:mysql://x:3306/wearable_device_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useOldAliasMetadataBehavior=true
    username: x
    password: x
    driverClassName: com.mysql.cj.jdbc.Driver

  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8

websocketServer:
  host: x
  port: 9094

alarmServer:
  port: 2012
  heartbeatTimeout: 50000